[package]
name = "asd-domain"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
indexmap = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
asd-ipc-protocol = { path = "../asd-ipc-protocol" }
